//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cars
    {
        public int Id { get; set; }
        public string LicencePlate { get; set; }
        public int Year { get; set; }
        public System.DateTime DateFabrication { get; set; }
        public bool New { get; set; }
        public bool Transmissions { get; set; }
        public int ModelId { get; set; }
    
        public virtual Models Models { get; set; }
    }
}
